# https://neo4j.com/docs/operations-manual/current/tutorial/tutorial-clustering-docker/
version: "3"

services:
  neo4j:
    image: neo4j:5.6.0
    environment:
      NEO4J_AUTH: neo4j/neo4jneo4j
    ports:
      - 7474:7474 # http
      - 7687:7687 # bolt
    volumes:
      - ./volumes/neo4j/data:/data
      - ./volumes/neo4j/imported_csv:/imported_csv
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1",
        ]
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 5

  # i2cf:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   environment:
  #     NEO4J_URL: neo4j://neo4j:7687
  #     NEO4J_USERNAME: neo4j
  #     NEO4J_PASSWORD: neo4j
  #     PORT: 8080
  #   depends_on:
  #     neo4j:
  #       condition: service_healthy
